### ISSUE TITLE
Support for Odyssey =)

### ISSUE THREAD

**Issue by CommandoCat** [poveden/EliteChroma#100]
As the title says. =)

**Comment by poveden** [comment]
Hi @CommandoCat! Actually, EliteChroma is Odyssey-ready (as far as I've tested). Just make sure that the _Game installation folder_ option in EliteChroma's settings points to the Odyssey folder, and not to the Horizons folder.

If you are not sure where Odyssey might be installed, look at [Frontier Support's article on file locations](https://customersupport.frontier.co.uk/hc/en-us/articles/360011817400-GAME-INSTALLATION-AND-FILE-LOCATIONS-NETLOG-APPCONFIG-CLIENT-LOG-UPDATE-LOG-GAME-FOLDER), and point to the `elite-dangerous-odyssey-64` folder instead of the `elite-dangerous-64` one.

Please confirm if it's working for you, or report back and I'll try to help you.

**Comment by tartanloon** [comment]
tried changing to the "elite-dangerous-odyssey-64" directory as suggested but EliteChroma crashes/exits abruptly when Odyssey starts for me.

anything else you can suggest?

thanks!

**Comment by CommandoCat** [comment]
Yeap! Same issue as tartanloon!

I already tried changing the directory. EliteChroma crashes/exits with no warning message.

**Comment by poveden** [comment]
Thanks for your feedback @tartanloon and @CommandoCat!

I believe that you may have encountered the same bug as in #101. I've put there a workaround while I work on a fix. Please try it and tell me if it works for you.

**Comment by CommandoCat** [comment]
Nice! That fixed it! Set the On-foot controls back to joypad (I actually customized my on-foot controls), but all you need to do is once you enter into game and ensure EliteChroma is still working, just go to options, on-foot controls, and select back "Custom".

I tried quitting Elite and starting it back up, EliteChroma stayed on and working, and my on-foot controls were back to my customized controls!
