### ISSUE TITLE
Add screenshot bindings

### ISSUE THREAD

**Issue by poveden** [poveden/EliteChroma#117]
_Originally posted by Frontier Forums user [aussi](https://forums.frontier.co.uk/members/aussi.19424/) via [Post](https://forums.frontier.co.uk/threads/elitechroma.534200/post-9433998):_

> Would you consider adding illumination for the screenshot key F10 (and Alt-F10)?

**Comment by aussig** [comment]
Could add non-bindable key combinations:

<kbd>F10</kbd> - Screenshot

<kbd>ALT</kbd>-<kbd>F10</kbd> - High resolution Screenshot (Does not work in Open Play)

<kbd>SHIFT</kbd>-<kbd>ALT</kbd>-<kbd>G</kbd> - Hide HUD (never got this one to work myself, possibly because I've got <kbd>SHIFT</kbd> bound to chat)

<kbd>CTRL</kbd>-<kbd>F</kbd> - Show framerate

<kbd>CTRL</kbd>-<kbd>B</kbd> - Show connection status

**Comment by poveden** [comment]
> <kbd>SHIFT</kbd>-<kbd>ALT</kbd>-<kbd>G</kbd> - Hide HUD (never got this one to work myself, possibly because I've got SHIFT bound to chat)

Actually, it's <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>G</kbd>.  Perhaps that's why it has never worked out for you. 😜
