### ISSUE TITLE
CTD - System.IO.InvalidDataException: Entry too large found in journal 

### ISSUE THREAD

**Issue by DarkmanReturns** [poveden/EliteChroma#142]
## Summary

EliteChroma stops working. This happens often (but not always) when I run EliteChroma in EDO.

Error message in Event Viewer is usually something like this one (events and journal attached):
Exception Info: System.IO.InvalidDataException: Entry too large found in journal 'Journal.2022-05-09T134508.01.log' at position 117788.

[EliteChromaCTD.txt](https://github.com/poveden/EliteChroma/files/8688516/EliteChromaCTD.txt)

## Steps to Reproduce

I don't get any kind of message when it crashes so I'm not sure if there is a specific action in game that triggers the CTD. 

## Expected Behavior

When it works it works flawlessly.

## Screenshots

No 

## Environment

- `EliteChroma` version: 1.16.1.0
- .NET Core version: 5.0.16
- Operating System: Win 10 Home

## Additional Context

[EliteChromaCTD.txt](https://github.com/poveden/EliteChroma/files/8688520/EliteChromaCTD.txt)
[Journal.2022-05-09T134508.01.log](https://github.com/poveden/EliteChroma/files/8688590/Journal.2022-05-09T134508.01.log)
[Journal.2022-05-13T141510.01.log](https://github.com/poveden/EliteChroma/files/8688944/Journal.2022-05-13T141510.01.log)

**Comment by poveden** [comment]
Hi! Thank you for reporting this. EliteChroma expects that each log entry is of a certain length, but clearly it's not enough. Could you please open that log file and tell me the length of the particular line where the error is being triggered? Alternatively, could you attach the log file here, so I can have a look at it?

**Comment by DarkmanReturns** [comment]
I _did_ attach the log file. It is showing in the Additional Context section.

The strange thing is that log file is from the 9th May, even though I'm playing on the 13th May and have a different log file for today.

**Comment by poveden** [comment]
The culprit seems to be the `StoredModules` event, which lists all the modules stored in a given system. In your case, you have 156 items (wow!) stored in Ohm City, LHS 20, which translates to a log entry of 41307 characters.

According to the [update 7 patch notes](https://brgeeks.com/elite-dangerous-odyssey-update-7-horizons-update-patch-notes/), the max number of modules is 200, which could make this entry grow up to around 53 KiB!

EliteChroma's buffer is [currently set at 32768 bytes](https://github.com/poveden/EliteChroma/blob/2e1070e5a593e467dbc26c31a44da08088c44f4e/src/EliteFiles/Journal/JournalReader.cs#L14). I'll increase this to 128 KiB, just to be on the safe side.

**Comment by DarkmanReturns** [comment]
1.16.2 is working fine, thank you. Tested for 15 minutes docking at different stations and making Outfitting changes with no CTD. I'm logging off to eat dinner now but will let you know if I run into any problems later.

**Comment by DarkmanReturns** [comment]
Another hour of testing with no issues. Marking this one as closed. Thank you again.
