### ISSUE TITLE
CTD - System.ArgumentException: Effect ID not found. (Parameter 'effectId')

### ISSUE THREAD

**Issue by DarkmanReturns** [poveden/EliteChroma#144]
## Summary

EliteChroma stops working. This happened this morning, I suspect when I started Horizons by mistake, then exited from Main Menu. The timestamps on the CTD and the log file would seem to support this theory.

## Expected Behavior

Does not CTD when exiting from Main Menu.

## Screenshots

None

## Environment

- `EliteChroma` version: 1.16.2
- .NET Core version: 5.0.16
- Operating System: Win 10 Home

## Additional Context

[Journal.220516103300.01.log](https://github.com/poveden/EliteChroma/files/8700817/Journal.220516103300.01.log)
[EliteChromaCTD_Effect ID not found.txt](https://github.com/poveden/EliteChroma/files/8700820/EliteChromaCTD_Effect.ID.not.found.txt)

**Comment by poveden** [comment]
Hi @DarkmanReturns! Thanks for reporting this. Actually you have just helped me to pinpoint the cause of this bug. It has happened to me just once, but couldn't reproduce until now.

The issue happens not because you closed the game without going further, but when you started the game again (Horizons, Odissey, it doesn't matter).

EliteChroma keeps track of the effects it creates on a given Razer Synapse "session" (one per each time the game is running), but currently it's not clearing the effect list between sessions. When the game starts for a second time, EliteChroma tries to delete the old effects, but they don't make sense on a new session, therefore the error.

I'll work on a fix and let you know when it's done.

**Comment by poveden** [comment]
[Release 1.16.3](https://github.com/poveden/EliteChroma/releases/tag/v1.16.3) is up with the fix. Please give it a try and let me know how it goes.

**Comment by DarkmanReturns** [comment]
Thank you again for the fix and the explanation.

I have tried and failed to reproduce the CTD in 1.16.3 with Horizons Main Menu > Exit to Desktop > Odyssey Main Menu > Odyssey Game and Odyssey Main Menu > Exit to Desktop > Odyssey Main Menu > Odyssey Game. 

Marking this one as Fixed too.
