### ISSUE TITLE
Use Tartarus V2 for lighting effects

### ISSUE THREAD

**Issue by Don-Chooluvit** [poveden/EliteChroma#68]
I have both a Blackwidow Elite and a Tartarus V2. The effects work on the Blackwidow, but not the Tartarus when using them at the same time. Would it be possible to implement the effects on the Tartarus as well?

**Comment by poveden** [comment]
Hi @Don-Chooluvit! The effects _should_ also work on the Tartarus, as I've implemented every Chroma device. Do _none_ of the effects appear? As far as I know, general background effects (like FSD jumps or being attacked) should work, but not individual keys (as it seems that the API doesn't support that).

**Comment by Don-Chooluvit** [comment]
It's weird, sometimes it works on both, then today only the Blackwidow works. The only animations I have seen so far are the fuel scooping and jumping (both AWESOME for the record). No effects on overheat, and I'm on my way back from Sagittarius A so I haven't seen anyone to pick a fight with yet, but I'll be there in 10K ly or so.

When should I start EliteChroma, before or after ED?

**Comment by poveden** [comment]
> When should I start EliteChroma, before or after ED?

It doesn't matter. EliteChroma will pick on the logs from ED, and update itself. You can let it run in the background whether ED is running or not, as it shouldn't barely consume any resources (if you note otherwise, please let me know!)

Every time EliteChroma receives an update from ED, it will send color information to the Razer Chroma RGB API that's in charge of lighting all appropriate devices. To my knowledge, there's no reason for it to work sometimes on one device, sometimes on another. Indeed, the only effects that you should see on the Tartarus are background effects, and should appear on _all_ devices at once.

Can you share with me a short video of the issue you're having? Maybe I can think of something.

**Comment by poveden** [comment]
> ... As far as I know, general background effects (like FSD jumps or being attacked) should work, ~but not individual keys (as it seems that the API doesn't support that).~

@Don-Chooluvit I've went through the documentation, and it's clear that individual keys in the Tartarus can be set. However, I don't know how these keys are recorded in ED's configuration files.

Could you please share with me your ED bindings file, so EliteChroma is able to light them also? Normally it's `Custom.3.0.binds`, and you should find it in the `%LOCALAPPDATA%\Frontier Developments\Elite Dangerous\Options\Bindings` folder.

**Comment by Don-Chooluvit** [comment]
I reassign almost all the keys, some with macros and not just key presses. I attached the binds and am willing to test. I use the Blackwidow and tartarus on my main machine, and just the tartarus on my laptop. I also finally saw the heat warning, which came on at 95% I think, so that works. 

Just rename the txt to binds.
[X52Elite - Custom.3.0.txt](https://github.com/poveden/EliteChroma/files/5578811/X52Elite.-.Custom.3.0.txt)

**Comment by poveden** [comment]
Thanks! It seems to me now that the Tartarus is not recognized in ED as a separate device, but rather the Tartarus simulates normal keyboard keypresses. Unless there's some way of retrieving the Tartarus mapping, I won't be able to light up ED bindings there. If you happen to know where Razer stores this, please let me know. I've created #69 to track this functionality, and for sure your helo will be welcome.

If you feel that there's something else I can do regarding the present topic, please let me know. If not, perhaps, we can close it.

**Comment by Cosmic-Pixels** [comment]
Hi, first of all congratulations for the work done, it is incredibly beautiful! Same thing from me, the tartarus stays with all orange keys and only produces animations about game events. It appears that it does not receive the custom colors for the set keys. It should receive the same colors from the Chroma app that the keyboard receives but not.
I would therefore suggest that you verify that the app tells chroma to color the keys on the keypad as well (which are seen by ED as a keyboard so I don't think I hang from ED).
Also, I would like to be able to  delete (until this problem is resolved) the tartarus from the management of EliteChroma so that I can assign my custom colors via razer studio. I will lose the animations on the game events but at least I will be able to distinguish the keys that I will color. Can you please explain how to eliminate Tartarus from devices managed by EliteChroma, if it is possible?
Thank you so much!!

**Comment by poveden** [comment]
@Cosmic-Pixels Thanks for your comments! As I mentioned earlier, EliteChroma only knows the bindings that Elite Dangerous describes in its configuration files, and the Tartarus keypad is not seen as a distinct device by ED, so I must either:

a. Find out a way to extract Tartarus bindings, or
b. Add a configuration section in EliteChroma to allow users to manually add keypad bindings.

I don't know at this time if it will be possible for meto implement option (a), but I've created #69 anyway to track this.

Regarding your suggestion to "remove" the Tartarus keypad from EliteChroma, I have the feeling it won't work due to the way the Razer SDK works, but we can try. If you are willing, I can create a modified version for you to test if it works. If you confirm, I'll move this discussion to a new thread.

**Comment by Cosmic-Pixels** [comment]
yes i can test it, thnaks!

**Comment by poveden** [comment]
Discussion moved to #69 and #78.
