### ISSUE TITLE
ambilight-like feature

### ISSUE THREAD

**Issue by mleonovvv** [poveden/EliteChroma#73]
Hi, thx for the nice utility. But, what about an ambilight-like feature based on Yeelight LED Lightstrip 1S? Its support razer chroma

**Comment by poveden** [comment]
Hi @mleonovvv! If your lightstrip is configured in Razer Synapse and is reacting to Synapse's settings, then EliteChroma should already light it up. Can you confirm this is the case?

**Comment by poveden** [comment]
@mleonovvv Any news?

**Comment by mleonovvv** [comment]
@poveden Hi, sorry for the long answer. Now I only have a light yeelight bulb. Yes, it works through the EliteChroma, But this is just a solid backlight. I mean ambilight. like this https://www.youtube.com/watch?v=BDNpbNbuLUU

**Comment by poveden** [comment]
As far as I understand, you cannot make the Yeelight Lightstrip 1S to show different colors at once. You can only apply the same color for the whole lightstrip, and I believe this to be true for every other lightstrip on the market (the [Philips Hue Play gradient lightstrip](https://www.philips-hue.com/en-us/products/all-products#filters=LIGHTSTRIPS_SU%2CFK_HUE_GRADIENT&page=1) being the exception, but it's _very_ expensive and I don't know if it will work with Razer Chroma).

**Comment by fudoido** [comment]
Razer recently launched a device that costs about 40£ (about the same value in dollars i believe) that you can plug any rgb strip brand into it and provide razer chroma animations and lighting to the strips. maybe is a better option considered its directly from razer?
https://www.razer.com/gb-en/gaming-pc-accessories/Razer-Chroma-Addressable-RGB-Controller/RZ34-02140600-R3U1

warning though, the led strips must be the same kind of what would provide addressable RGB lightning, where each led can have individual colour and/or on/off individually (think their code is WS2812B?) Something like this.....
https://www.amazon.co.uk/CHINLY-144leds-Individually-addressable-Waterproof/dp/B07TQS9JN9/ref=sr_1_49_sspa?crid=30C7VVEGY64B0&dchild=1&keywords=rgb+5050+led+strip&qid=1611448647&refinements=p_76%3A419158031&rnid=419157031&rps=1&sprefix=rgb+5050%2Caps%2C146&sr=8-49-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExOVJBNFpJMFZaR1c5JmVuY3J5cHRlZElkPUEwNDUwMzcwSVBHNEg0MlpMUVY0JmVuY3J5cHRlZEFkSWQ9QTA2MjU2NjMzSUREUEVLTU04MkNSJndpZGdldE5hbWU9c3BfYnRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

When i get a chance to buy them, i am intending to do a infinity mirror/clock powered by elite animations :)

**Comment by poveden** [comment]
> When i get a chance to buy them, i am intending to do a infinity mirror/clock powered by elite animations :)

Nice! Please share your setup when you do. However, I must warn you that, regardless of the capabilities of the Razer RGB controller, [the Chroma SDK currently only allows setting 5 different colors at any given time](https://developer.razer.com/works-with-chroma/chroma-link-guide/). How that reflects on the ARGB strips attached to that controller remains to be seen.

**Comment by fudoido** [comment]
im quite sure that the animations and effects will still be great to watch. lets see if the world starts running normal again so i can feel a bit more free to spend the money. currently have to save in case i run out of work, which so far has not happened.

**Comment by fudoido** [comment]
small update on this feature.
i recently got an msi motherboard which has 1 slot for addressable rgb leds, plus some argb leds on the board itself and using crucial ballistix tracer rgb memory.
by using synapse, the set is identified as a single device. with elitechroma the colors keep the orange hue while iddle and show the blue color animations when entering supercruise or jumping. also shows red color animations when ship gets heat damage.
it does not offer a ambilight feature though, but was wondering if that could be possible since synapse has a feature of its own in the rgb studio, named "ambient awareness", where you can select parts of the screen and gathers info of the most dominant color on screen and reflects it into the rgb led. I selected a small region in the center to catch up warnings red colour, for example.
my question now is, would it be possible to keep that feature while using elitechroma and make elitechroma only show animations for some warnings, such as the fuel scooping, or heat damage, etc. The synapse feature makes a more responsive animation since its linked to screen colours, so stars passing by while cruising/jumping look a little more realistic.
would be great to keep that synapse feature active for motherboard/ram/strips/fans (whatever is connected to motherboard, i mean) and use the elitechroma animations for keyboard only and/or other peripherals or for special events.

**Comment by poveden** [comment]
I've created #96 to track an AmbiLight/Ambient Awareness feature. Closing this now. Thanks for your feedback!
