### ISSUE TITLE
Can't Locate Installation Folder for Epic Games

### ISSUE THREAD

**Issue by prodig41** [poveden/EliteChroma#87]
## Summary

When I try to run the program it can't detect the installation folder. It's installed to C:\Program Files\Epic Games\EliteDangerous

## Steps to Reproduce

I've installed the .NET and the latest version of Synapse. When I run EliteChroma it states that it is unable to locate all folders.

## Expected Behavior

Game detects installation folder.

**Comment by prodig41** [comment]
![Snip](https://user-images.githubusercontent.com/77367678/104393068-64851d00-54f8-11eb-875b-8ff33b3b260e.PNG)

**Comment by poveden** [comment]
Thanks for reporting this. According to this [FAQ article on Frontier's Customer Support site](https://customersupport.frontier.co.uk/hc/en-us/articles/360011817400-Game-installation-and-file-locations-Netlog-AppConfig-Client-Log-Update-Log-Game-Folder-) (reachable from the "game install" link on EliteChroma's configuration dialog), the right folder is:

```
C:\Program Files\Epic Games\EliteDangerous\Products\elite-dangerous-64
```

I understand that what I call "game installation folder" does not correspond with Frontier's definition. That's due to the fact that there are more "games" under their installation folder, e.g.:

- Main game: `«Game installation folder»\Products\elite-dangerous-64`
- Demo and tutorial: `«Game installation folder»\Products\COMBAT_TUTORIAL_DEMO`
- Beta test game: `«Game installation folder»\Products\PUBLIC_TEST_SERVER_64`

To be fair, I wasn't aware that the FAQ article was updated just 2 months ago (where they surely added the Epic Games folder), so the previous version of it may have had some different wording, adding to the confusion.

I'll add the Epic Games folder to EliteChroma's detection list, and try to make it a little bit more smart and pick the right folder based on Frontier's definition.

**Comment by prodig41** [comment]
Hey! Thank you so much, sorry for the confusion on my end. Really cool that you're putting in all this work for us, many thanks CMDR!

**Comment by Rovetown** [comment]
Sorry to comment on this one, but in order for Odyssey to work you need to set the path to **elite-dangerous-odyssey-64** and not **elite-dangerous-64**

For anyone who has Problems with it not working.

**Comment by poveden** [comment]
> Sorry to comment on this one, but in order for Odyssey to work you need to set the path to **elite-dangerous-odyssey-64** and not **elite-dangerous-64**

Thanks for this comment. Just to let you know that, as of version 1.12.0, there's a drop-down list in the "game installation folder" field that shows all discovered folders. Hopefully this will make the choice a little bit more evident.
